### ISSUE TITLE
DA rest calls return empty jsons

### ISSUE THREAD

**Issue by cwjoshuak** [FoothillCSClub/OwlAPI#34]
any call for example
`/da/list?dept=CIS`
will return ""

**Comment by phi-line** [comment]
Okay, you'll have to excuse this time period while we wait for new classes to get added into the system for summer. Right now, we are approaching 'Second Spring' and there are a very few number of sections available:

<img width="703" alt="screen shot 2018-05-11 at 12 08 53 am" src="https://user-images.githubusercontent.com/19956136/39911254-a3b8106e-54af-11e8-96f6-427873db06ac.png">

As you can see, there are no courses available in the second spring for `CIS`.

One issue with how they update the data is that when second spring comes, they **temporarily overwrite** the the data for Spring quarter. We are working on an issue to mine all past quarters too so that there will never be this problem.

Also, this issue brings to mind that the API shouldn't make a new key if it cannot find any more than one entry in the table. In other words, if an entry like `CIS` does not have any sections, it shouldn't show up in `/list`.

I'll go ahead and make another issue. In the meantime - stay tight. We are working on another data miner that can retrieve all past quarter's data.

**Comment by phi-line** [comment]
@cwjoshuak I've added a `test` campus into Production. This is an old copy of Foothill data that you can use in the meantime while we sync the server with MyPortal data. We are still figuring out a way to elegantly handle past data.

Good news is that summer quarter data has dropped for both De Anza and Foothill. I will be performing the migration to summer data soon within the next week. Until then, feel free to use the `test` campus like in this example:

> `GET /test/list?dept=CS`

**Comment by phi-line** [comment]
Fixed with #49
